// Code generated by mockery v2.33.2. DO NOT EDIT.

package mocks

import (
	cli "github.com/urfave/cli/v2"

	mock "github.com/stretchr/testify/mock"
)

// IPingCommands is an autogenerated mock type for the IPingCommands type
type IPingCommands struct {
	mock.Mock
}

// GetPingController provides a mock function with given fields: c
func (_m *IPingCommands) GetPingController(c *cli.Context) error {
	ret := _m.Called(c)

	var r0 error
	if rf, ok := ret.Get(0).(func(*cli.Context) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetPingRepository provides a mock function with given fields: c
func (_m *IPingCommands) GetPingRepository(c *cli.Context) error {
	ret := _m.Called(c)

	var r0 error
	if rf, ok := ret.Get(0).(func(*cli.Context) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetPingUseCase provides a mock function with given fields: c
func (_m *IPingCommands) GetPingUseCase(c *cli.Context) error {
	ret := _m.Called(c)

	var r0 error
	if rf, ok := ret.Get(0).(func(*cli.Context) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIPingCommands creates a new instance of IPingCommands. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIPingCommands(t interface {
	mock.TestingT
	Cleanup(func())
}) *IPingCommands {
	mock := &IPingCommands{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
