// Code generated by mockery v2.33.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IMysqlWriter is an autogenerated mock type for the IMysqlWriter type
type IMysqlWriter struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *IMysqlWriter) Close() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIMysqlWriter creates a new instance of IMysqlWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIMysqlWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *IMysqlWriter {
	mock := &IMysqlWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
