// Code generated by mockery v2.33.2. DO NOT EDIT.

package mocks

import (
	entities "simple-invitation/domain/entities"

	mock "github.com/stretchr/testify/mock"

	sql "database/sql"

	time "time"

	uuid "github.com/google/uuid"
)

// IGatheringRepository is an autogenerated mock type for the IGatheringRepository type
type IGatheringRepository struct {
	mock.Mock
}

// CreateNewGathering provides a mock function with given fields: attendees, creator, gatheringTypeName, gatheringName, gatheringLocation, scheduled_at
func (_m *IGatheringRepository) CreateNewGathering(attendees []*entities.Member, creator *entities.Member, gatheringTypeName string, gatheringName string, gatheringLocation string, scheduled_at time.Time) (*entities.Gathering, error) {
	ret := _m.Called(attendees, creator, gatheringTypeName, gatheringName, gatheringLocation, scheduled_at)

	var r0 *entities.Gathering
	var r1 error
	if rf, ok := ret.Get(0).(func([]*entities.Member, *entities.Member, string, string, string, time.Time) (*entities.Gathering, error)); ok {
		return rf(attendees, creator, gatheringTypeName, gatheringName, gatheringLocation, scheduled_at)
	}
	if rf, ok := ret.Get(0).(func([]*entities.Member, *entities.Member, string, string, string, time.Time) *entities.Gathering); ok {
		r0 = rf(attendees, creator, gatheringTypeName, gatheringName, gatheringLocation, scheduled_at)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Gathering)
		}
	}

	if rf, ok := ret.Get(1).(func([]*entities.Member, *entities.Member, string, string, string, time.Time) error); ok {
		r1 = rf(attendees, creator, gatheringTypeName, gatheringName, gatheringLocation, scheduled_at)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchDBReader provides a mock function with given fields:
func (_m *IGatheringRepository) FetchDBReader() *sql.DB {
	ret := _m.Called()

	var r0 *sql.DB
	if rf, ok := ret.Get(0).(func() *sql.DB); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.DB)
		}
	}

	return r0
}

// FetchDBWriter provides a mock function with given fields:
func (_m *IGatheringRepository) FetchDBWriter() *sql.DB {
	ret := _m.Called()

	var r0 *sql.DB
	if rf, ok := ret.Get(0).(func() *sql.DB); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.DB)
		}
	}

	return r0
}

// FetchGatheringTypeById provides a mock function with given fields: idGatheringType
func (_m *IGatheringRepository) FetchGatheringTypeById(idGatheringType uuid.UUID) (*entities.GatheringType, error) {
	ret := _m.Called(idGatheringType)

	var r0 *entities.GatheringType
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (*entities.GatheringType, error)); ok {
		return rf(idGatheringType)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) *entities.GatheringType); ok {
		r0 = rf(idGatheringType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.GatheringType)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(idGatheringType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchGatheringTypeByName provides a mock function with given fields: gatheringTypeName
func (_m *IGatheringRepository) FetchGatheringTypeByName(gatheringTypeName string) (*entities.GatheringType, error) {
	ret := _m.Called(gatheringTypeName)

	var r0 *entities.GatheringType
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*entities.GatheringType, error)); ok {
		return rf(gatheringTypeName)
	}
	if rf, ok := ret.Get(0).(func(string) *entities.GatheringType); ok {
		r0 = rf(gatheringTypeName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.GatheringType)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(gatheringTypeName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchGatheringTypes provides a mock function with given fields:
func (_m *IGatheringRepository) FetchGatheringTypes() ([]*entities.GatheringType, error) {
	ret := _m.Called()

	var r0 []*entities.GatheringType
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*entities.GatheringType, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*entities.GatheringType); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.GatheringType)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchInvitationStatusById provides a mock function with given fields: invitationStatusId
func (_m *IGatheringRepository) FetchInvitationStatusById(invitationStatusId uuid.UUID) (*entities.InvitationStatus, error) {
	ret := _m.Called(invitationStatusId)

	var r0 *entities.InvitationStatus
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (*entities.InvitationStatus, error)); ok {
		return rf(invitationStatusId)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) *entities.InvitationStatus); ok {
		r0 = rf(invitationStatusId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.InvitationStatus)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(invitationStatusId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchInvitationStatuses provides a mock function with given fields:
func (_m *IGatheringRepository) FetchInvitationStatuses() ([]*entities.InvitationStatus, error) {
	ret := _m.Called()

	var r0 []*entities.InvitationStatus
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*entities.InvitationStatus, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*entities.InvitationStatus); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.InvitationStatus)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StoreInvitationStatus provides a mock function with given fields: name
func (_m *IGatheringRepository) StoreInvitationStatus(name string) (*entities.InvitationStatus, error) {
	ret := _m.Called(name)

	var r0 *entities.InvitationStatus
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*entities.InvitationStatus, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) *entities.InvitationStatus); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.InvitationStatus)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StoreNewGatheringType provides a mock function with given fields: name
func (_m *IGatheringRepository) StoreNewGatheringType(name string) (*entities.GatheringType, error) {
	ret := _m.Called(name)

	var r0 *entities.GatheringType
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*entities.GatheringType, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) *entities.GatheringType); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.GatheringType)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIGatheringRepository creates a new instance of IGatheringRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIGatheringRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IGatheringRepository {
	mock := &IGatheringRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
