version: "3.1"
services:
  # api:
  #   build:
  #     context: ../../backend/api
  #     dockerfile: ./Dockerfile
  #   restart: on-failure
  #   environment:
  #     - STAGE_STATUS="dev"
  #     - HOSTNAME="app-x1x1-xxxxx"
  #     - DB_HOST=10.5.0.5
  #     - DB_PORT=5432
  #     - DB_USER="shamir"
  #     - DB_PASSWORD="password"
  #     - DB_NAME="cgapp-postgres"
  #     - DB_SSL_MODE="disable"
  #     - DB_MAX_CONNECTIONS=100
  #     - DB_MAX_IDLE_CONNECTIONS=3
  #     - DB_MAX_LIFETIME_CONNECTIONS=2
  #     - DB_TIMEZONE="UTC"
  #     - SERVER_HOST="0.0.0.0"
  #     - SERVER_PORT=5000
  #     - SERVER_READ_TIMEOUT=60
  #     - ETCD_DSN="10.5.0.6:2379,10.5.0.6:2380"
  #   ports:
  #     - 5000:5000
  db:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    expose:
      - "3306"
    environment:
      MARIADB_ROOT_PASSWORD: "root"
      MARIADB_DATABASE: "simpleinvitation"
      MARIADB_USER: "rani"
      MARIADB_PASSWORD: "rani"
