// Code generated by mockery v2.33.2. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// IGatheringController is an autogenerated mock type for the IGatheringController type
type IGatheringController struct {
	mock.Mock
}

// CreateNewGathering provides a mock function with given fields: c
func (_m *IGatheringController) CreateNewGathering(c *gin.Context) {
	_m.Called(c)
}

// FetchGatheringTypeById provides a mock function with given fields: c
func (_m *IGatheringController) FetchGatheringTypeById(c *gin.Context) {
	_m.Called(c)
}

// FetchGatheringTypes provides a mock function with given fields: c
func (_m *IGatheringController) FetchGatheringTypes(c *gin.Context) {
	_m.Called(c)
}

// FetchInvitationStatusById provides a mock function with given fields: c
func (_m *IGatheringController) FetchInvitationStatusById(c *gin.Context) {
	_m.Called(c)
}

// FetchInvitationStatuses provides a mock function with given fields: c
func (_m *IGatheringController) FetchInvitationStatuses(c *gin.Context) {
	_m.Called(c)
}

// StoreInvitationStatus provides a mock function with given fields: c
func (_m *IGatheringController) StoreInvitationStatus(c *gin.Context) {
	_m.Called(c)
}

// StoreNewGatheringType provides a mock function with given fields: c
func (_m *IGatheringController) StoreNewGatheringType(c *gin.Context) {
	_m.Called(c)
}

// NewIGatheringController creates a new instance of IGatheringController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIGatheringController(t interface {
	mock.TestingT
	Cleanup(func())
}) *IGatheringController {
	mock := &IGatheringController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
