// Code generated by mockery v2.33.2. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// IMemberController is an autogenerated mock type for the IMemberController type
type IMemberController struct {
	mock.Mock
}

// FetchAll provides a mock function with given fields: c
func (_m *IMemberController) FetchAll(c *gin.Context) {
	_m.Called(c)
}

// FetchMemberByEmail provides a mock function with given fields: c
func (_m *IMemberController) FetchMemberByEmail(c *gin.Context) {
	_m.Called(c)
}

// FetchMemberById provides a mock function with given fields: c
func (_m *IMemberController) FetchMemberById(c *gin.Context) {
	_m.Called(c)
}

// StoreNewMeber provides a mock function with given fields: c
func (_m *IMemberController) StoreNewMeber(c *gin.Context) {
	_m.Called(c)
}

// NewIMemberController creates a new instance of IMemberController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIMemberController(t interface {
	mock.TestingT
	Cleanup(func())
}) *IMemberController {
	mock := &IMemberController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
