// Code generated by mockery v2.33.2. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// IPingController is an autogenerated mock type for the IPingController type
type IPingController struct {
	mock.Mock
}

// GetPingController provides a mock function with given fields: c
func (_m *IPingController) GetPingController(c *gin.Context) {
	_m.Called(c)
}

// GetPingRepository provides a mock function with given fields: c
func (_m *IPingController) GetPingRepository(c *gin.Context) {
	_m.Called(c)
}

// GetPingUseCase provides a mock function with given fields: c
func (_m *IPingController) GetPingUseCase(c *gin.Context) {
	_m.Called(c)
}

// NewIPingController creates a new instance of IPingController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIPingController(t interface {
	mock.TestingT
	Cleanup(func())
}) *IPingController {
	mock := &IPingController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
