// Code generated by mockery v2.33.2. DO NOT EDIT.

package mocks

import (
	context "context"
	compiled "simple-invitation/protocol/grpc/presenters/compiled"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"
)

// MemberServiceClient is an autogenerated mock type for the MemberServiceClient type
type MemberServiceClient struct {
	mock.Mock
}

// FetchAll provides a mock function with given fields: ctx, in, opts
func (_m *MemberServiceClient) FetchAll(ctx context.Context, in *compiled.MemberRequest, opts ...grpc.CallOption) (*compiled.MemberResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *compiled.MemberResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *compiled.MemberRequest, ...grpc.CallOption) (*compiled.MemberResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *compiled.MemberRequest, ...grpc.CallOption) *compiled.MemberResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*compiled.MemberResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *compiled.MemberRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMemberServiceClient creates a new instance of MemberServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMemberServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MemberServiceClient {
	mock := &MemberServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
