// Code generated by mockery v2.33.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IMysqlReader is an autogenerated mock type for the IMysqlReader type
type IMysqlReader struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *IMysqlReader) Close() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIMysqlReader creates a new instance of IMysqlReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIMysqlReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *IMysqlReader {
	mock := &IMysqlReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
